name: Maven Package

on:
  release:
    types: [created]

  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven

    - name: Build with Maven
      run: mvn -B package -DskipTests --file OnderhoudsbuddyJava/pom.xml

    - name: Upload build artifact
      uses: actions/upload-artifact@v4
      with:
        name: OnderhoudsbuddyJava-package
        path: OnderhoudsbuddyJava/target/*.jar
