# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Maven Package

on:
  release:
    types: [created]

  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file

    - name: Build with Maven (skip tests)
      run: mvn -B package -DskipTests --file OnderhoudsbuddyJava/pom.xml

    - name: Run tests with detailed output
      run: mvn -B test --file OnderhoudsbuddyJava/pom.xml
      continue-on-error: true

    - name: Upload test reports
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: surefire-reports
        path: OnderhoudsbuddyJava/target/surefire-reports/

    - name: Publish to GitHub Packages Apache Maven
      if: success()
      run: mvn deploy -s $GITHUB_WORKSPACE/settings.xml --file OnderhoudsbuddyJava/pom.xml -DskipTests
      env:
        GITHUB_TOKEN: ${{ github.token }}
