name: Node.js CI - OnderhoudsbuddyFrontend

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Debug: toon inhoud van directories
        run: |
          ls -la
          ls -la OB
          ls -la OB/onderhoudsbuddyfrontend

      - name: Install dependencies
        working-directory: OB/onderhoudsbuddyfrontend
        run: npm ci

      - name: Build frontend
        working-directory: OB/onderhoudsbuddyfrontend
        run: npm run build --if-present

      - name: Run tests
        working-directory: OB/onderhoudsbuddyfrontend
        run: npm test
